services:
  # Backend API Service
  - type: web
    name: capstone-backend
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MILVUS_URI
        sync: false
      - key: MILVUS_TOKEN
        sync: false
      - key: MILVUS_DB
        value: capstone
      - key: MILVUS_COLLECTION
        value: kb_chunks
      - key: LOG_LEVEL
        value: INFO

  # Frontend Static Site
  - type: web
    name: capstone-frontend
    runtime: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: capstone-backend
          property: url